---

- name: Install Docker on Linux 
  hosts: all
  become: yes
  tasks:

    - name: Clean apt cache
      shell: apt autoremove -y && apt clean all
      when: ansible_facts['os_family'] == "Debian"

    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install prrequisites 
      apt:
        name:
          - curl
          - ca-certificates
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Create directory for apt keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      when: ansible_facts['os_family'] == "Debian"

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
      when: ansible_facts['os_family'] == "Debian"

    - name: Add Docker repository 
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
        https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \"${UBUNTU_CODENAME:-$VERSION_CODENAME}\") stable" \
        | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /etc/apt/sources.list.d/docker.list
      when: ansible_facts['os_family'] == "Debian"

    - name: Update apt cache after adding Docker repository
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Docker packages 
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install dnf-plugins-core
      dnf:
        name: dnf-plugins-core
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Add Docker repository 
      shell: |
        dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install Docker packages 
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      when: ansible_facts['os_family'] == "RedHat"


    - name: Enable and start Docker service
      service:
        name: docker
        state: started
        enabled: yes
