- name: Update Cache (Debian)
  apt:
    update_cache: yes
  tags: [update_cache_debian]
  when: ansible_facts['os_family'] == "Debian"

- name: Update Cache (RedHat)
  dnf:
    update_cache: yes
  tags: [update_cache_redhat]
  when: ansible_facts['os_family'] == "RedHat"

- name: Install ssh packages (Debian)
  apt:
    name:
      - openssh-server
      - openssh-client
  tags: [install_ssh_packages_debian]
  when: ansible_facts['os_family'] == "Debian"

- name: Install ssh packages (RedHat)
  dnf:
    name:
      - openssh-server
      - openssh-client
  tags: [install_ssh_packages_redhat]
  when: ansible_facts['os_family'] == "RedHat"

- name: Copy sshd config file
  copy:
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config.backup
    remote_src: yes
    owner: root
    group: root
    mode: 0644
  tags: [copy_sshd_config_file]

- name: Change sshd config file
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#PermitRootLogin (no|prohibit-password)"
    line: "PermitRootLogin yes"
    state: present
  tags: [change_sshd_config_file]

- name: Enable and restart ssh service (Debian)
  systemd:
    name: ssh
    daemon_reload: yes
    state: restarted
    enabled: yes
  tags: [enable_and_restart_ssh_service_debian]
  when: ansible_facts['os_family'] == "Debian"

- name: Enable and restart sshd service (RedHat)
  systemd:
    name: sshd
    daemon_reload: yes
    state: restarted
    enabled: yes
  tags: [enable_and_restart_sshd_service_redhat]
  when: ansible_facts['os_family'] == "RedHat"


